import { createClient } from 'npm:@supabase/supabase-js@2'

const ALLOWED_ORIGINS=new Set(['https://globall-cloud.pages.dev','https://globall-cloud.netlify.app'])
const WINDOW_MS=10*60*1000
const MAX_PER_WINDOW=30
const buckets=new Map<string,{start:number,count:number}>()
const text=(v:unknown,max=120)=>String(v??'').trim().slice(0,max)
const num=(v:unknown)=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null}
const clientKey=(req:Request)=>(req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')||'unknown').split(',')[0].trim().slice(0,80)
const rateLimited=(key:string)=>{const now=Date.now();const c=buckets.get(key);if(!c||now-c.start>=WINDOW_MS){buckets.set(key,{start:now,count:1});return false}if(c.count>=MAX_PER_WINDOW)return true;c.count++;return false}
const headers=(req:Request)=>{const o=req.headers.get('origin')||'';return {'Content-Type':'application/json; charset=utf-8',...(ALLOWED_ORIGINS.has(o)?{'Access-Control-Allow-Origin':o}:{}),'Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'}}
const reply=(req:Request,b:Record<string,unknown>,s=200)=>new Response(JSON.stringify(b),{status:s,headers:headers(req)})
const service=()=>{const url=Deno.env.get('SUPABASE_URL');const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY');if(!url||!key)throw new Error('Server pricing configuration unavailable');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})}
Deno.serve(async(req)=>{const origin=req.headers.get('origin')||'';if(origin&&!ALLOWED_ORIGINS.has(origin))return reply(req,{error:'Origin not allowed'},403);if(req.method==='OPTIONS')return new Response('ok',{headers:headers(req)});if(req.method!=='POST')return reply(req,{error:'Method not allowed'},405);if(rateLimited(clientKey(req)))return reply(req,{error:'Too many requests. Please try again later.'},429);try{const b=await req.json().catch(()=>({}));const product=text(b.product_type,80).toLowerCase()||'general';const originKey=text(b.origin_key,80).toLowerCase();const destKey=text(b.destination_key,80).toLowerCase()||'erbil';const mode=text(b.transport_mode,30).toLowerCase()||'air';const weight=num(b.weight_kg);const volume=num(b.volume_cbm);const db=service();const compliance=await db.rpc('validate_logistics_cargo',{p_product_type:product,p_has_battery:b.has_battery===true,p_has_liquid:b.has_liquid===true,p_msds_provided:b.msds_provided===true,p_medical_device:b.medical_device===true});if(compliance.error)throw compliance.error;if(!compliance.data?.allowed)return reply(req,{allowed:false,message_ku:compliance.data?.message_ku||'کاڵاکە وەرناگیرێت.'},200);if((mode==='sea'&&!(volume&&volume>0))||(mode!=='sea'&&!(weight&&weight>0)))return reply(req,{error:'Weight or volume is required.'},400);const result=await db.rpc('calculate_logistics_price',{p_origin_key:originKey,p_destination_key:destKey,p_transport_mode:mode,p_product_type:product,p_weight_kg:weight,p_volume_cbm:volume,p_rate_key:null});if(result.error)throw result.error;return reply(req,{allowed:true,quote:result.data||null},200)}catch(e){console.error('[public-pricing]',e instanceof Error?e.message:String(e));return reply(req,{error:'Unable to calculate price right now.'},500)}})