import { createClient } from 'npm:@supabase/supabase-js@2'

const ORIGINS = new Set(['https://globall-cloud.pages.dev','https://globall-cloud.netlify.app'])
const STAFF = new Set(['super_admin','admin','accountant','finance','warehouse','warehouse_china','warehouse_uae','warehouse_erbil','operations','driver','delivery'])
const ADMIN = new Set(['super_admin','admin'])
const FINANCE = new Set(['super_admin','admin','accountant','finance'])
const OPS = new Set(['super_admin','admin','operations','warehouse','warehouse_china','warehouse_uae','warehouse_erbil','driver','delivery'])

const cors=(req:Request)=>({
  'Access-Control-Allow-Origin':ORIGINS.has(req.headers.get('origin')||'')?req.headers.get('origin')!:'https://globall-cloud.pages.dev',
  'Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info,x-supabase-auth-token,x-idempotency-key',
  'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'
})
const json=(req:Request,b:unknown,status=200)=>new Response(JSON.stringify(b),{status,headers:{'Content-Type':'application/json; charset=utf-8',...cors(req)}})
const txt=(v:unknown)=>{const s=String(v??'').trim();return s||null}
const num=(v:unknown)=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
const gc=(v:unknown)=>{const s=txt(v);if(!s)return null;const n=s.normalize('NFKC').toUpperCase().replace(/[–—−]/g,'-').replace(/\s+/g,'');return /^GC-[A-Z0-9-]{2,30}$/.test(n)?n:null}
const isAdmin=(r:string)=>ADMIN.has(r)

async function actor(req:Request){
 const url=Deno.env.get('SUPABASE_URL')||'', anon=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY')||'', secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY')||''
 const authHeader=req.headers.get('authorization')||''
 if(!url||!anon||!secret||!/^Bearer\s+/i.test(authHeader))throw Error('Unauthorized')
 const ac=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{headers:{Authorization:authHeader}}})
 const {data:u,error:ue}=await ac.auth.getUser();if(ue||!u.user)throw Error('Unauthorized')
 const db=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
 const {data:s,error:se}=await db.from('staff').select('id,full_name,role,branch,is_active,email').eq('id',u.user.id).maybeSingle();if(se)throw se
 if(!s?.is_active||!STAFF.has(String(s.role)))throw Error('Forbidden')
 return {db,user:u.user,staff:s,role:String(s.role)}
}
async function audit(a:any,action:string,targetId:string|null,details:any={}){const r=await a.db.from('staff_activity_log').insert({staff_id:a.staff.id,staff_name:a.staff.full_name,action,target_id:targetId,details:JSON.stringify(details)});if(r.error)console.warn('audit',r.error.message)}

async function getShipments(a:any){const {data,error}=await a.db.from('shipments').select('*').order('created_at',{ascending:false}).limit(2000);if(error)throw error;return data||[]}
async function getCustomers(a:any){const {data,error}=await a.db.from('customer_directory').select('*').order('created_at',{ascending:false}).limit(5000);if(error)throw error;return data||[]}
async function getPricing(a:any){const [r,f,p]=await Promise.all([a.db.from('pricing_rates').select('*').order('origin_key').order('transport_mode').order('product_type'),a.db.from('exchange_rates').select('*').order('created_at',{ascending:false}).limit(100),a.db.from('pricing_rules').select('*').order('created_at',{ascending:false})]);if(r.error)throw r.error;if(f.error)throw f.error;if(p.error)throw p.error;return{rates:r.data||[],exchange_rates:f.data||[],rules:p.data||[]}}
async function getFinance(a:any){const [t,c,cost]=await Promise.all([a.db.from('finance_transactions').select('*').order('created_at',{ascending:false}).limit(5000),a.db.from('customers').select('gc_code,name,balance,debt,status').limit(5000),a.db.from('company_costs').select('*').order('occurred_at',{ascending:false}).limit(5000)]);if(t.error)throw t.error;if(c.error)throw c.error;return{transactions:t.data||[],customers:c.data||[],company_costs:cost.error?[]:cost.data||[]}}
async function getAlerts(a:any){const {data,error}=await a.db.from('staff_alerts').select('*').order('created_at',{ascending:false}).limit(500);if(error)throw error;return(data||[]).filter((x:any)=>(!x.audience_role||String(x.audience_role)===a.role)&&!(Array.isArray(x.read_by)&&x.read_by.map(String).includes(String(a.staff.id))))}
async function getWarehouses(a:any){const [w,r,m]=await Promise.all([a.db.from('warehouse_locations').select('*').order('city').order('name'),a.db.from('warehouse_receipts').select('*').order('received_at',{ascending:false}).limit(500),a.db.from('warehouse_movements').select('*').order('scanned_at',{ascending:false}).limit(500)]);if(w.error)throw w.error;if(r.error)throw r.error;if(m.error)throw m.error;return{warehouses:w.data||[],receipts:r.data||[],movements:m.data||[]}}
async function getActivity(a:any){const {data,error}=await a.db.from('staff_activity_log').select('*').order('created_at',{ascending:false}).limit(1500);if(error)throw error;return data||[]}
async function getChats(a:any,customer=false){if(customer){const {data:t,error:e}=await a.db.from('customer_chat_threads').select('*').order('last_message_at',{ascending:false}).limit(500);if(e)throw e;const ids=(t||[]).map((x:any)=>x.id);let messages:any[]=[];if(ids.length){const r=await a.db.from('customer_chat_messages').select('*').in('thread_id',ids).order('created_at',{ascending:true}).limit(5000);if(r.error)throw r.error;messages=r.data||[]}return{threads:t||[],messages}}const {data:rooms,error:re}=await a.db.from('staff_chat_rooms').select('*').order('updated_at',{ascending:false});if(re)throw re;const ids=(rooms||[]).map((x:any)=>x.id);let messages:any[]=[];if(ids.length){const r=await a.db.from('staff_chat_messages').select('*').in('room_id',ids).order('created_at',{ascending:true}).limit(5000);if(r.error)throw r.error;messages=r.data||[]}return{rooms:rooms||[],messages}}
async function getRequests(a:any){const [q,r]=await Promise.all([a.db.from('quote_requests').select('*').order('created_at',{ascending:false}).limit(500),a.db.from('admin_action_requests').select('*').order('created_at',{ascending:false}).limit(500)]);if(q.error)throw q.error;if(r.error)throw r.error;return{quote_requests:q.data||[],admin_requests:r.data||[]}}
async function getAnalytics(a:any){const [s,t,c,fx,st]=await Promise.all([a.db.from('shipments').select('id,total_amount,paid_amount,transport_mode,origin_key,dest_key,assigned_staff_id,operational_status,archived_at,created_at').limit(5000),a.db.from('finance_transactions').select('type,amount_usd,created_at,gc_code').limit(5000),a.db.from('company_costs').select('amount_iqd,origin_key,dest_key,staff_id,occurred_at').limit(5000),a.db.from('exchange_rates').select('rate,usd_to_iqd,is_active,created_at').order('created_at',{ascending:false}).limit(20),a.db.from('staff').select('id,full_name,role,branch,is_active').limit(500)]);if(s.error)throw s.error;if(t.error)throw t.error;if(c.error)throw c.error;if(st.error)throw st.error;const rate=Number((fx.data||[]).find((x:any)=>x.is_active)?.rate||(fx.data||[])[0]?.rate||(fx.data||[])[0]?.usd_to_iqd||0);const live=(s.data||[]).filter((x:any)=>!x.archived_at);const revenue=live.reduce((n:number,x:any)=>n+Number(x.total_amount||0),0);const collected=live.reduce((n:number,x:any)=>n+Number(x.paid_amount||0),0);const txIncome=(t.data||[]).filter((x:any)=>!['expense','cost','out'].includes(String(x.type).toLowerCase())).reduce((n:number,x:any)=>n+Number(x.amount_usd||0),0);const txExpense=(t.data||[]).filter((x:any)=>['expense','cost','out'].includes(String(x.type).toLowerCase())).reduce((n:number,x:any)=>n+Number(x.amount_usd||0),0);const iqdCost=(c.data||[]).reduce((n:number,x:any)=>n+Number(x.amount_iqd||0),0);const costUsd=rate>0?iqdCost/rate:0;const byRoute=new Map<string,any>();for(const x of live){const k=`${x.origin_key||x.origin||'—'} → ${x.dest_key||x.destination||'—'}`;const r=byRoute.get(k)||{route:k,shipments:0,revenue:0,outstanding:0};r.shipments++;r.revenue+=Number(x.total_amount||0);r.outstanding+=Math.max(0,Number(x.total_amount||0)-Number(x.paid_amount||0));byRoute.set(k,r)}const byStaff=new Map<string,any>();for(const x of st.data||[]){byStaff.set(String(x.id),{id:x.id,name:x.full_name,role:x.role,branch:x.branch,active:x.is_active,shipments:0,delivered:0})}for(const x of live){const k=String(x.assigned_staff_id||'');const r=byStaff.get(k);if(r){r.shipments++;if(['delivered','completed'].includes(String(x.operational_status||'').toLowerCase()))r.delivered++}}return{fx_rate:rate,summary:{shipments:live.length,revenue_usd:revenue,collected_usd:collected,outstanding_usd:Math.max(0,revenue-collected),finance_income_usd:txIncome,finance_expense_usd:txExpense,company_cost_usd:costUsd,estimated_profit_usd:revenue+txIncome-txExpense-costUsd},routes:[...byRoute.values()].sort((x,y)=>y.revenue-x.revenue),staff:[...byStaff.values()].sort((x,y)=>(y.delivered*10+y.shipments)-(x.delivered*10+x.shipments))}}

async function post(a:any,action:string,d:any){
 if(action==='customer_create'){if(!ADMIN.has(a.role))throw Error('Admin permission required');const code=gc(d.gc_code||d.code)||`GC-${Math.floor(1000+Math.random()*9000)}`;const email=txt(d.email)||`${code.toLowerCase()}@globall-cloud.local`;const password=txt(d.password)||crypto.randomUUID().replace(/-/g,'').slice(0,12)+'Aa!';const u=await a.db.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:txt(d.name)||'Customer',phone:txt(d.phone),gc_code:code}});if(u.error)throw u.error;const r=await a.db.from('customer_directory').insert({code,gc_code:code,normalized_gc_code:code,name:txt(d.name)||'Customer',phone:txt(d.phone)||'',phone2:txt(d.phone2),email,auth_user_id:u.data.user.id,is_active:true,city:txt(d.city),delivery_location:txt(d.delivery_location),note:txt(d.note),preferred_language:txt(d.preferred_language)||'ckb',preferred_contact_channel:txt(d.preferred_contact_channel)||'whatsapp'}).select('*').single();if(r.error){await a.db.auth.admin.deleteUser(u.data.user.id);throw r.error}await audit(a,'customer.create',r.data.id,{gc_code:code});return{customer:r.data,temporary_password:password}}
 if(action==='customer_update'||action==='customer_disable'||action==='customer_enable'){if(!ADMIN.has(a.role))throw Error('Admin permission required');const id=txt(d.id);if(!id)throw Error('Customer id is required');const p:any={updated_at:new Date().toISOString()};for(const k of ['name','phone','phone2','email','city','delivery_location','note','preferred_language','preferred_contact_channel'])if(d[k]!==undefined)p[k]=txt(d[k]);if(action==='customer_disable')p.is_active=false;if(action==='customer_enable')p.is_active=true;const r=await a.db.from('customer_directory').update(p).eq('id',id).select('*').single();if(r.error)throw r.error;await audit(a,`customer.${action.replace('customer_','')}`,id,p);return{customer:r.data}}
 if(action==='customer_reset_password'){if(!ADMIN.has(a.role))throw Error('Admin permission required');const id=txt(d.id);const password=txt(d.password)||crypto.randomUUID().replace(/-/g,'').slice(0,12)+'Aa!';const r=await a.db.auth.admin.updateUserById(id,{password});if(r.error)throw r.error;await audit(a,'customer.password_reset',id,{});return{temporary_password:password}}
 if(action==='pricing_create'||action==='pricing_update'||action==='pricing_disable'){if(!['super_admin','admin','accountant'].includes(a.role))throw Error('Pricing permission required');if(action==='pricing_create'){const amount=num(d.amount);if(amount===null||amount<0)throw Error('Invalid price');const key=txt(d.rate_key)||`${txt(d.transport_mode)}_${txt(d.origin_key)}_${txt(d.destination_key)}_${txt(d.product_type)}`.toLowerCase().replace(/[^a-z0-9]+/g,'_');const r=await a.db.from('pricing_rates').insert({rate_key:key,origin_key:txt(d.origin_key),destination_key:txt(d.destination_key),transport_mode:txt(d.transport_mode),product_type:txt(d.product_type),unit:txt(d.unit)||'kg',amount,currency:txt(d.currency)||'USD',transit_min_days:num(d.transit_min_days),transit_max_days:num(d.transit_max_days),effective_from:txt(d.effective_from)||new Date().toISOString().slice(0,10),is_active:d.is_active!==false,notes:txt(d.notes),markup_percent:num(d.markup_percent)||0,created_by:a.staff.id,updated_by:a.staff.id}).select('*').single();if(r.error)throw r.error;await audit(a,'pricing.create',r.data.id,{key,amount});return{rate:r.data}}const id=txt(d.id);if(!id)throw Error('Rate id is required');const p:any={updated_at:new Date().toISOString(),updated_by:a.staff.id};for(const k of ['amount','transit_min_days','transit_max_days','notes','markup_percent','is_active','product_type','unit'])if(d[k]!==undefined)p[k]=k==='amount'||k==='transit_min_days'||k==='transit_max_days'||k==='markup_percent'?num(d[k]):(k==='is_active'?Boolean(d[k]):txt(d[k]));if(action==='pricing_disable')p.is_active=false;const r=await a.db.from('pricing_rates').update(p).eq('id',id).select('*').single();if(r.error)throw r.error;await audit(a,`pricing.${action.replace('pricing_','')}`,id,p);return{rate:r.data}}
 if(action==='fx_set'){if(!['super_admin','admin','accountant'].includes(a.role))throw Error('Pricing permission required');const rate=num(d.usd_to_iqd);if(rate===null||rate<=0)throw Error('Invalid FX rate');const r=await a.db.from('exchange_rates').insert({usd_to_iqd:rate,rate,base_currency:'USD',quote_currency:'IQD',source:txt(d.source)||'manual',effective_on:new Date().toISOString().slice(0,10),effective_from:new Date().toISOString().slice(0,10),is_active:true,updated_by:a.staff.id,updated_at:new Date().toISOString()}).select('*').single();if(r.error)throw r.error;await audit(a,'fx.update',r.data.id,{rate});return{rate:r.data}}
 if(action==='shipment_update'){if(!OPS.has(a.role))throw Error('Shipment permission required');const id=txt(d.id);if(!id)throw Error('Shipment id is required');const l=num(d.length_cm),w=num(d.width_cm),h=num(d.height_cm),actual=num(d.actual_weight_kg),vol=l&&w&&h?l*w*h/6000:null;const p:any={updated_at:new Date().toISOString()};for(const k of ['status','operational_status','transport_mode','origin_warehouse','destination_warehouse','cargo_description','carton_count','actual_weight_kg','length_cm','width_cm','height_cm','chargeable_weight_kg','current_location_label','eta','priority','assigned_staff_id'])if(d[k]!==undefined)p[k]=k==='carton_count'||k.endsWith('_kg')?num(d[k]):['status','operational_status','transport_mode','origin_warehouse','destination_warehouse','cargo_description','current_location_label','priority'].includes(k)?txt(d[k]):d[k];p.volumetric_weight_kg=vol;if(p.chargeable_weight_kg==null)p.chargeable_weight_kg=Math.max(Number(actual||0),Number(vol||0));const r=await a.db.from('shipments').update(p).eq('id',id).select('*').single();if(r.error)throw r.error;await audit(a,'shipment.update',id,p);return{shipment:r.data}}
 if(action==='tracking_add'){if(!OPS.has(a.role))throw Error('Tracking permission required');const id=txt(d.shipment_id);if(!id)throw Error('Shipment id is required');const e={shipment_id:id,status_key:txt(d.status_key||d.status)||'in_transit',title:txt(d.title)||'Tracking update',note:txt(d.note),location_label:txt(d.location_label),lat:num(d.lat),lng:num(d.lng),occurred_at:txt(d.occurred_at)||new Date().toISOString(),photos:Array.isArray(d.photos)?d.photos:[],created_by:a.staff.id,created_by_name:a.staff.full_name,is_public:d.is_public!==false,metadata:d.metadata&&typeof d.metadata==='object'?d.metadata:{}};const r=await a.db.from('shipment_tracking_events').insert(e).select('*').single();if(r.error)throw r.error;await a.db.from('shipments').update({operational_status:e.status_key,current_location_label:e.location_label,tracking_updated_at:e.occurred_at,updated_at:new Date().toISOString()}).eq('id',id);const s=await a.db.from('shipments').select('customer_user_id,customer_gc_code').eq('id',id).maybeSingle();if(s.data?.customer_user_id)await a.db.from('customer_notifications').insert({customer_user_id:s.data.customer_user_id,shipment_id:id,kind:'tracking_update',event_key:`tracking:${id}:${r.data.id}`,title:e.title,body:e.note||e.location_label||e.status_key,action_url:`/track?gc=${encodeURIComponent(s.data.customer_gc_code||'')}`});await audit(a,'tracking.add',id,{event_id:r.data.id,status_key:e.status_key});return{event:r.data}}
 if(action==='warehouse_move'){if(!OPS.has(a.role))throw Error('Warehouse permission required');const r=await a.db.rpc('record_warehouse_movement',{p_actor_id:a.staff.id,p_shipment_id:txt(d.shipment_id),p_package_id:txt(d.package_id),p_receipt_id:txt(d.receipt_id),p_from_hub:txt(d.from_hub),p_to_hub:txt(d.to_hub||d.location),p_movement_type:txt(d.movement_type)||'transfer',p_scan_code:gc(d.scan_code),p_notes:txt(d.notes),p_metadata:d.metadata&&typeof d.metadata==='object'?d.metadata:{},p_idempotency_key:txt(d.idempotency_key)||crypto.randomUUID()});if(r.error)throw r.error;await audit(a,'warehouse.move',txt(d.shipment_id),{result:r.data});return{movement:r.data}}
 if(action==='alert_create'){if(!ADMIN.has(a.role))throw Error('Admin permission required');const r=await a.db.from('staff_alerts').insert({kind:txt(d.kind)||'info',title:txt(d.title)||'Alert',body:txt(d.body),entity_type:txt(d.entity_type),entity_id:txt(d.entity_id),action_url:txt(d.action_url),severity:txt(d.severity)||'normal',audience_role:txt(d.audience_role),read_by:[]}).select('*').single();if(r.error)throw r.error;await audit(a,'alert.create',r.data.id,{severity:r.data.severity});return{alert:r.data}}
 if(action==='alert_read'){const id=txt(d.id);if(!id)throw Error('Alert id is required');const r=await a.db.from('staff_alerts').select('read_by').eq('id',id).single();if(r.error)throw r.error;const readBy=Array.isArray(r.data.read_by)?r.data.read_by.map(String):[];if(!readBy.includes(String(a.staff.id)))readBy.push(String(a.staff.id));const u=await a.db.from('staff_alerts').update({read_by:readBy}).eq('id',id);if(u.error)throw u.error;return{ok:true}}
 if(action==='finance_create'||action==='finance_update'){if(!FINANCE.has(a.role))throw Error('Finance permission required');if(action==='finance_create'){const amount=num(d.amount_usd);if(amount===null||amount<0)throw Error('Invalid finance amount');const r=await a.db.from('finance_transactions').insert({type:txt(d.type)||'income',gc_code:gc(d.gc_code),amount_usd:amount,created_at:txt(d.created_at)||new Date().toISOString()}).select('*').single();if(r.error)throw r.error;await audit(a,'finance.create',r.data.id,{amount_usd:amount,type:r.data.type});return{transaction:r.data}}const id=txt(d.id),amount=num(d.amount_usd);if(!id||amount===null||amount<0)throw Error('Invalid finance data');const r=await a.db.from('finance_transactions').update({type:txt(d.type)||'income',gc_code:gc(d.gc_code),amount_usd:amount}).eq('id',id).select('*').single();if(r.error)throw r.error;await audit(a,'finance.update',id,{amount_usd:amount});return{transaction:r.data}}
 if(action==='staff_chat_send'){if(!STAFF.has(a.role))throw Error('Chat permission required');const body=txt(d.body);if(!body)throw Error('Message body is required');let room=txt(d.room_id);if(!room){const r=await a.db.from('staff_chat_rooms').insert({slug:`room-${crypto.randomUUID().slice(0,8)}`,name:txt(d.room_name)||'Staff',description:txt(d.description),is_active:true,created_by:a.staff.id}).select('id').single();if(r.error)throw r.error;room=r.data.id}const r=await a.db.from('staff_chat_messages').insert({room_id:room,sender_id:a.staff.id,body,client_message_id:txt(d.client_message_id)}).select('*').single();if(r.error)throw r.error;await a.db.from('staff_chat_rooms').update({updated_at:new Date().toISOString()}).eq('id',room);return{message:r.data,room_id:room}}
 if(action==='customer_chat_send'){if(!STAFF.has(a.role))throw Error('Chat permission required');const body=txt(d.body),customerId=txt(d.customer_user_id);if(!body||!customerId)throw Error('Customer and message are required');let thread=txt(d.thread_id);if(!thread){const r=await a.db.from('customer_chat_threads').insert({customer_user_id:customerId,gc_code:gc(d.gc_code),subject:txt(d.subject)||'Support',status:'open',priority:txt(d.priority)||'normal',assigned_staff_id:a.staff.id}).select('id').single();if(r.error)throw r.error;thread=r.data.id}const r=await a.db.from('customer_chat_messages').insert({thread_id:thread,sender_user_id:a.user.id,sender_type:'staff',body,attachments:Array.isArray(d.attachments)?d.attachments:[]}).select('*').single();if(r.error)throw r.error;await a.db.from('customer_chat_threads').update({last_message_at:new Date().toISOString(),updated_at:new Date().toISOString(),assigned_staff_id:a.staff.id}).eq('id',thread);return{message:r.data,thread_id:thread}}
 if(action==='profile_update'){const p:any={};for(const k of ['full_name','job_title','phone','locale','timezone'])if(d[k]!==undefined)p[k]=txt(d[k]);if(d.full_name!==undefined){const r=await a.db.from('staff').update({full_name:txt(d.full_name)||a.staff.full_name,updated_at:new Date().toISOString()}).eq('id',a.staff.id);if(r.error)throw r.error;delete p.full_name}if(Object.keys(p).length){const r=await a.db.from('staff_profiles').upsert({staff_id:a.staff.id,...p,updated_at:new Date().toISOString()},{onConflict:'staff_id'});if(r.error)throw r.error}await audit(a,'profile.update',a.staff.id,{fields:Object.keys(d)});return{ok:true}}
 if(action==='password_change'){const password=txt(d.password);if(!password||password.length<8)throw Error('Password must be at least 8 characters');const r=await a.db.auth.admin.updateUserById(a.user.id,{password});if(r.error)throw r.error;await audit(a,'profile.password_change',a.staff.id,{});return{ok:true}}
 throw Error('Unsupported action')
}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});try{const a=await actor(req);if(req.method==='GET'){const u=new URL(req.url),k=txt(u.searchParams.get('kind'))||'health';if(k==='shipments')return json(req,{items:await getShipments(a)});if(k==='shipment'){const id=txt(u.searchParams.get('id'));if(!id)throw Error('Shipment id is required');return json(req,await (async()=>{const x=await a.db.from('shipments').select('*').eq('id',id).maybeSingle();if(x.error)throw x.error;if(!x.data)throw Error('Shipment not found');const[p,e,r,i,l]=await Promise.all([a.db.from('shipment_packages').select('*').eq('shipment_id',id).order('created_at',{ascending:false}),a.db.from('shipment_tracking_events').select('*').eq('shipment_id',id).order('created_at',{ascending:false}),a.db.from('warehouse_receipts').select('*').eq('shipment_id',id).order('received_at',{ascending:false}),a.db.from('shipment_insurance').select('*').eq('shipment_id',id).order('purchased_at',{ascending:false}),a.db.from('shipment_financial_ledger').select('*').eq('shipment_id',id).order('created_at',{ascending:false})]);for(const z of [p,e,r,i,l])if(z.error)throw z.error;return{shipment:x.data,packages:p.data||[],events:e.data||[],receipts:r.data||[],insurance:i.data||[],ledger:l.data||[]}})());if(k==='customers')return json(req,{items:await getCustomers(a)});if(k==='pricing')return json(req,await getPricing(a));if(k==='finance')return json(req,await getFinance(a));if(k==='alerts')return json(req,{items:await getAlerts(a)});if(k==='warehouses')return json(req,await getWarehouses(a));if(k==='activity')return json(req,{items:await getActivity(a)});if(k==='staff-chat')return json(req,await getChats(a,false));if(k==='customer-chat')return json(req,await getChats(a,true));if(k==='requests')return json(req,await getRequests(a));if(k==='analytics')return json(req,await getAnalytics(a));if(k==='profile')return json(req,{staff:a.staff});return json(req,{ok:true,service:'staff-production-api',role:a.role,time:new Date().toISOString()})}const b=await req.json().catch(()=>({}));return json(req,await post(a,txt(b.action)||'',b.data||{}))}catch(e){const m=e instanceof Error?e.message:String(e);const s=/Unauthorized/i.test(m)?401:/Forbidden|permission/i.test(m)?403:/required|Invalid|Unsupported|not found/i.test(m)?400:500;return json(req,{error:m},s)}})
