(()=>{
'use strict';
const API='https://ahslifnthiwfkmaswjno.supabase.co';
const KEY='sb_publishable_M4UtzEbCLwMCd9LanFWw5g_5b7-fWda';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let lang=localStorage.getItem('gc-lang')||'ku';
if(!['ku','en'].includes(lang)) lang='ku';
const dict={ku:{home:'سەرەکی',shipments:'بارەکان',track:'شوێنکەوتن',routes:'ڕێڕەو و خزمەتگوزاری',quote:'داواکردنی نرخ',profile:'پڕۆفایل',welcome:'بەخێربێیت بۆ Global Cloud',headline:'گەیاندنی بار بە کۆنترۆڵی ڕاستەقینە',sub:'چین و ئیمارات → هەولێر و هەموو عێراق',trackNow:'شوێنکەوتنی بار',newQuote:'داواکردنی نرخ',active:'بارە چالاکەکەت',network:'نەخشەی ڕێڕەوی کار',noShipment:'هیچ بارێک هەڵنەگیراوە',trackingHint:'ژمارەی شوێنکەوتن بنووسە',search:'گەڕان',send:'ناردنی داواکاری',routeTitle:'هەڵبژاردنی ڕێڕەو',origin:'سەرەتا',destination:'مەبەست',services:'خزمەتگوزارییەکان'},en:{home:'Home',shipments:'Shipments',track:'Track',routes:'Routes & Services',quote:'Quote',profile:'Profile',welcome:'Welcome to Global Cloud',headline:'Move cargo with real operational control',sub:'China & UAE → Erbil and across Iraq',trackNow:'Track shipment',newQuote:'Request a quote',active:'Active shipment',network:'Live logistics corridor',noShipment:'No shipment loaded',trackingHint:'Enter tracking number',search:'Search',send:'Send request',routeTitle:'Choose route',origin:'Origin',destination:'Destination',services:'Services'}};
function applyLang(){const t=dict[lang];document.documentElement.lang=lang==='ku'?'ckb':'en';document.documentElement.dir=lang==='ku'?'rtl':'ltr';$$('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;e.textContent=t[k]||e.textContent});$$('[data-i18n-placeholder]').forEach(e=>{const k=e.dataset.i18nPlaceholder;e.placeholder=t[k]||e.placeholder});const l=$('#langBtn');if(l)l.textContent=lang==='ku'?'KU / EN':'EN / KU';localStorage.setItem('gc-lang',lang)}
function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('[data-screen-target]').forEach(b=>b.classList.toggle('active',b.dataset.screenTarget===name));const titles={home:dict[lang].home,shipments:dict[lang].shipments,track:dict[lang].track,routes:dict[lang].routes,quote:dict[lang].quote,profile:dict[lang].profile};$('#screenTitle').textContent=titles[name]||titles.home;window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+name)}
function escapeHTML(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function theme(){const light=localStorage.getItem('gc-theme')==='light';document.documentElement.dataset.theme=light?'light':'dark';}
async function track(idOverride){const id=(idOverride||$('#trackInput').value||'').trim();const out=$('#trackResult');if(!id){out.textContent=dict[lang].trackingHint;out.className='track-result error';return}showScreen('track');$('#trackInput').value=id;out.textContent=lang==='ku'?'لە سێرڤەری production دەگەڕێم...':'Checking production tracking service...';out.className='track-result';try{const r=await fetch(`${API}/functions/v1/public-track?id=${encodeURIComponent(id)}`,{headers:{apikey:KEY,Accept:'application/json'},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);const s=d.shipment||{};const ev=d.events||[];$('#trackSummary').innerHTML=`<div class="screen-card-title"><h3>${escapeHTML(s.id||id)}</h3><span class="status">${escapeHTML(s.status||s.status_key||'Active')}</span></div><div class="shipment-route"><div><small>ORIGIN</small><b>${escapeHTML(s.origin_key||'—')}</b></div><div><small>DESTINATION</small><b>${escapeHTML(s.dest_key||'—')}</b></div><div><small>LOCATION</small><b>${escapeHTML(s.current_location_label||'—')}</b></div></div>`;$('#timeline').innerHTML=ev.length?ev.slice(0,8).map((e,i)=>`<div class="timeline-item"><span class="timeline-dot"></span><div><b>${escapeHTML(e.title||e.status_key||`Update ${i+1}`)}</b><small>${escapeHTML(e.location_label||'')} ${e.occurred_at?'· '+escapeHTML(new Date(e.occurred_at).toLocaleString()):''}</small></div></div>`).join(''):`<div class="timeline-item"><span class="timeline-dot"></span><div><b>${lang==='ku'?'هیچ event ـێکی زیاتر نییە':'No additional events'}</b><small>—</small></div></div>`;out.textContent=lang==='ku'?'بارەکە بە سەرکەوتوویی دۆزرایەوە.':'Shipment loaded successfully.';out.className='track-result success';localStorage.setItem('gc-last-track',id)}catch(e){out.textContent=(lang==='ku'?'کێشە: ':'Error: ')+e.message;out.className='track-result error'}}
async function quote(e){e.preventDefault();const f=e.currentTarget;const out=$('#quoteResult');const body=Object.fromEntries(new FormData(f).entries());out.textContent=lang==='ku'?'لە server ـی production دەنێردرێت...':'Sending to production server...';try{const r=await fetch(`${API}/functions/v1/public-message`,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);out.textContent=lang==='ku'?'داواکاریەکەت بە سەرکەوتوویی نێردرا.':'Request sent successfully.';f.reset()}catch(err){out.textContent=(lang==='ku'?'کێشە: ':'Error: ')+err.message}}
function init(){applyLang();theme();const hash=location.hash.replace('#','');showScreen(['home','shipments','track','routes','quote','profile'].includes(hash)?hash:'home');$$('[data-screen-target]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screenTarget)));$('#langBtn')?.addEventListener('click',()=>{lang=lang==='ku'?'en':'ku';applyLang();showScreen(location.hash.replace('#','')||'home')});$('#themeBtn')?.addEventListener('click',()=>{localStorage.setItem('gc-theme',localStorage.getItem('gc-theme')==='light'?'dark':'light');theme()});$('#trackBtn')?.addEventListener('click',()=>track());$('#trackInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')track()});$('#quoteForm')?.addEventListener('submit',quote);$$('[data-route]').forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.route;$('#selectedRoute').textContent=name;showScreen('quote')}));const last=localStorage.getItem('gc-last-track');if(last){$('#homeLastTrack').textContent=last;$('#trackInput').value=last}}
window.addEventListener('hashchange',()=>{const h=location.hash.replace('#','');if(['home','shipments','track','routes','quote','profile'].includes(h))showScreen(h)});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();