(() => {
'use strict';
const SUPABASE_URL='https://ahslifnthiwfkmaswjno.supabase.co';
const SUPABASE_KEY='sb_publishable_M4UtzEbCLwMCd9LanFWw5g_5b7-fWda';
const TRACK_URL=`${SUPABASE_URL}/functions/v1/public-track`;
const CONFIG_URL=`${SUPABASE_URL}/functions/v1/public-config?key=usd_iqd_rate`;
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const I18N={
ku:{lang:'KU',navHome:'سەرەکی',navTrack:'شوێنکەوتن',navServices:'خزمەتگوزاری',navWarehouses:'کۆگاکان',navContact:'پەیوەندی',navStaff:'ستاف',badge:'LIVE LOGISTICS CORRIDOR',hero:'گەیاندنی بار بە متمانە، خێرایی و کۆنترۆڵی ڕاستەقینە',hero2:'لە چین و ئیمارات بۆ هەولێر و هەموو عێراق — لە وەرگرتن و کۆگا تا گومرک، شوێنکەوتن و گەیاندن.',track:'شوێنکەوتنی بار',quote:'داواکاری نرخی بار',note:'شوێنکەوتنی عمومی پشت بە server ـی Supabase ـی production دەبەستێت.',trust1:'باری گەیەنراو',trust2:'هاب',trust3:'پشتیوانی',trust4:'کۆنترۆڵی داتا',trackKick:'شوێنکەوتنی ڕاستەوخۆ',trackH:'ژمارەی شوێنکەوتنت بنووسە',trackP:'نمونە: GC-10052341',trackBtn:'بگەڕێ',empty:'ژمارەی شوێنکەوتن بنووسە.',servicesKick:'خزمەتگوزاری',servicesH:'سیستەمێکی تەواو بۆ زنجیرەی لۆجستیک',servicesP:'Air، Sea، Door-to-Door، گومرک، کۆگا، tracking و کۆنترۆڵی ناوخۆ لە یەک platform ـدا.',air:'Air Cargo',sea:'Sea Cargo',customs:'گومرک و clearance',warehouse:'کۆگا و QC',tracking:'Live Tracking',ops:'Operations OS',hubsKick:'GLOBAL CLOUD NETWORK',hubsH:'سێ هابی سەرەکی',guangzhou:'گوانگجو · چین',dubai:'دوبەی · ئیمارات',erbil:'هەولێر · عێراق',quoteH:'داواکاری نرخی کار',quoteP:'داتاکانت بنێرە؛ تیمی لۆجستیک بە نرخ و ڕێگای گەیاندن وەڵامت دەداتەوە.',name:'ناو',phone:'مۆبایل',route:'ڕێگا',weight:'کێش (kg)',goods:'جۆری کاڵا',quoteBtn:'ناردنی داواکاری',routePlaceholder:'China → Dubai → Erbil',goodsPlaceholder:'مثلاً electronic accessories',contactH:'پەیوەندی ڕاستەوخۆ',contactP:'بۆ وەڵامی خێرا بە واتساپ پەیوەندیمان پێوە بکە.',wa:'واتساپ',email:'ئیمەیل',staff:'کۆنسۆڵی ستاف'},
en:{lang:'EN',navHome:'Home',navTrack:'Tracking',navServices:'Services',navWarehouses:'Hubs',navContact:'Contact',navStaff:'Staff',badge:'LIVE LOGISTICS CORRIDOR',hero:'Move cargo with trust, speed and real operational control',hero2:'China and UAE to Erbil and across Iraq — from pickup and warehousing to customs, tracking and delivery.',track:'Track shipment',quote:'Request a quote',note:'Public tracking is powered by the production Supabase backend.',trust1:'Shipments delivered',trust2:'Core hubs',trust3:'Support',trust4:'Data control',trackKick:'REAL-TIME TRACKING',trackH:'Enter your tracking number',trackP:'Example: GC-10052341',trackBtn:'Track',empty:'Enter a tracking number.',servicesKick:'SERVICES',servicesH:'One operating system for the logistics chain',servicesP:'Air, Sea, Door-to-Door, customs, warehousing, tracking and internal operations in one platform.',air:'Air Cargo',sea:'Sea Cargo',customs:'Customs & clearance',warehouse:'Warehouse & QC',tracking:'Live Tracking',ops:'Operations OS',hubsKick:'GLOBAL CLOUD NETWORK',hubsH:'Three core hubs',guangzhou:'Guangzhou · China',dubai:'Dubai · UAE',erbil:'Erbil · Iraq',quoteH:'Request a logistics quote',quoteP:'Send the basics and our team will respond with routing and pricing.',name:'Name',phone:'Phone',route:'Route',weight:'Weight (kg)',goods:'Goods type',quoteBtn:'Send request',routePlaceholder:'China → Dubai → Erbil',goodsPlaceholder:'e.g. electronic accessories',contactH:'Direct contact',contactP:'For a fast response, contact us on WhatsApp.',wa:'WhatsApp',email:'Email',staff:'Staff console'}};
let lang=localStorage.getItem('gc-lang')||'ku';if(!I18N[lang])lang='ku';
const flash=msg=>{const e=$('#flash');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(window.__flashTimer);window.__flashTimer=setTimeout(()=>e.classList.remove('show'),2800)};
function setText(){const t=I18N[lang];$$('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(k in t)e.textContent=t[k]});$$('[data-i18n-placeholder]').forEach(e=>{const k=e.dataset.i18nPlaceholder;if(k in t)e.placeholder=t[k]});document.documentElement.lang=lang==='ku'?'ckb':'en';document.documentElement.dir=lang==='ku'?'rtl':'ltr';$('#langBtn').textContent=t.lang;const a=$('#trackingInput');if(a)a.placeholder=t.trackP}
function toggleLang(){lang=lang==='ku'?'en':'ku';localStorage.setItem('gc-lang',lang);setText()}
function toggleTheme(){const light=document.documentElement.dataset.theme==='light';document.documentElement.dataset.theme=light?'dark':'light';localStorage.setItem('gc-theme',light?'dark':'light');$('#themeBtn').textContent=light?'◐':'☀️'}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function formatTime(v){try{return new Date(v).toLocaleString(lang==='ku'?'ku-IQ':'en-GB',{dateStyle:'medium',timeStyle:'short'})}catch{return String(v||'')}}
function renderTracking(data){const box=$('#trackingResult'),s=data.shipment,events=Array.isArray(data.events)?data.events:[];box.className='result ok';box.innerHTML=`<strong>${lang==='ku'?'بارەکە دۆزرایەوە':'Shipment found'}: ${escapeHtml(s.id)}</strong><div style="margin-top:8px;color:var(--muted)">${escapeHtml(s.origin_key||'Origin')} → ${escapeHtml(s.dest_key||'Destination')} · ${escapeHtml(s.transport_mode||'logistics')} ${s.weight_kg?` · ${escapeHtml(s.weight_kg)} kg`:''}</div><div class="timeline">${events.slice(0,6).map(e=>`<div class="event"><strong>${escapeHtml(e.title||e.status_key||'Update')}</strong><div>${escapeHtml(e.location_label||'')}</div><small>${formatTime(e.occurred_at||e.created_at)}</small></div>`).join('')}</div>`}
async function trackShipment(){const id=($('#trackingInput').value||'').trim(),box=$('#trackingResult');if(!id){box.className='result err';box.textContent=I18N[lang].empty;return}box.className='result';box.textContent=lang==='ku'?'گەڕان لە server ـی production...':'Checking production tracking service...';try{const r=await fetch(`${TRACK_URL}?id=${encodeURIComponent(id)}`,{headers:{apikey:SUPABASE_KEY,Accept:'application/json'},cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);renderTracking(data)}catch(e){box.className='result err';box.textContent=lang==='ku'?`نەدۆزرایەوە: ${e.message}`:`Not found: ${e.message}`}}
function openWhatsApp(){const msg=lang==='ku'?'سڵاو Globall Cloud، دەمەوێ داواکاری نرخی ناردنی بار بکەم.':'Hello Globall Cloud, I would like to request a shipping quote.';window.open(`https://wa.me/9647507577137?text=${encodeURIComponent(msg)}`,'_blank','noopener')}
function submitQuote(ev){ev.preventDefault();const v=Object.fromEntries(new FormData(ev.currentTarget).entries()),msg=lang==='ku'?`داواکاری نرخی بار\nناو: ${v.name}\nمۆبایل: ${v.phone}\nڕێگا: ${v.route}\nکێش: ${v.weight} kg\nکاڵا: ${v.goods}`:`Quote request\nName: ${v.name}\nPhone: ${v.phone}\nRoute: ${v.route}\nWeight: ${v.weight} kg\nGoods: ${v.goods}`;window.open(`https://wa.me/9647507577137?text=${encodeURIComponent(msg)}`,'_blank','noopener');flash(lang==='ku'?'داواکارییەکە بۆ واتساپ ئامادە کرا.':'Quote request prepared for WhatsApp.');ev.currentTarget.reset()}
async function loadRateHealth(){try{const r=await fetch(CONFIG_URL,{headers:{apikey:SUPABASE_KEY,Accept:'application/json'},cache:'no-store'});if(r.ok){const d=$('#liveDot');if(d)d.title='Supabase production online'}}catch{}}
function boot(){const saved=localStorage.getItem('gc-theme');if(saved)document.documentElement.dataset.theme=saved;setText();$('#langBtn').addEventListener('click',toggleLang);$('#themeBtn').addEventListener('click',toggleTheme);$('#trackBtn').addEventListener('click',trackShipment);$('#trackingInput').addEventListener('keydown',e=>{if(e.key==='Enter')trackShipment()});$('#quoteForm').addEventListener('submit',submitQuote);$('#waBtn').addEventListener('click',openWhatsApp);$('#themeBtn').textContent=document.documentElement.dataset.theme==='light'?'☀️':'◐';loadRateHealth()}
boot();
})();
