(() => {
  'use strict';
  const state={lang:localStorage.getItem('gc-lang')==='en'?'en':'ku',route:'china',theme:localStorage.getItem('gc-theme')||'dark'};
  const SUPA='https://ahslifnthiwfkmaswjno.supabase.co';
  const KEY='sb_publishable_M4UtzEbCLwMCd9LanFWw5g_5b7-fWda';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function applyLang(){document.documentElement.lang=state.lang==='ku'?'ckb':'en';document.documentElement.dir=state.lang==='ku'?'rtl':'ltr';localStorage.setItem('gc-lang',state.lang);$$('[data-ku]').forEach(e=>e.textContent=e.dataset[state.lang]);}
  function applyTheme(){document.documentElement.dataset.theme=state.theme;localStorage.setItem('gc-theme',state.theme);}
  function initMenu(){const btn=$('#gcMenu'),panel=$('#gcMenuPanel');btn?.addEventListener('click',()=>{panel.hidden=!panel.hidden});$$('#gcMenuPanel a').forEach(a=>a.addEventListener('click',()=>{panel.hidden=true;}));}
  function initMap(){const el=$('#gcMap');if(!el)return;if(!window.L){el.innerHTML='<div style="padding:24px;color:#9eb3c8">Map service unavailable.</div>';return;}const map=L.map(el,{scrollWheelZoom:false,zoomControl:true}).setView([28,58],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);const hubs=[{name:'Guangzhou · China',coords:[23.1291,113.2644],flag:'🇨🇳'},{name:'Dubai · UAE',coords:[25.2048,55.2708],flag:'🇦🇪'},{name:'Erbil · Iraq',coords:[36.1911,44.0092],flag:'🇮🇶'}];const pin=emoji=>L.divIcon({className:'gc-pin',html:`<div style="width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#0b223c;border:2px solid #29d7e8;box-shadow:0 8px 20px rgba(0,0,0,.3);font-size:20px">${emoji}</div>`,iconSize:[38,38],iconAnchor:[19,19]});hubs.forEach(h=>L.marker(h.coords,{icon:pin(h.flag)}).addTo(map).bindPopup(`<b>${safe(h.name)}</b>`));L.polyline(hubs.map(h=>h.coords),{color:'#29d7e8',weight:3,opacity:.85,dashArray:'8 8'}).addTo(map);map.fitBounds(L.latLngBounds(hubs.map(h=>h.coords)).pad(.2));window.gcMap=map;}
  function initRoutes(){$$('.gc-route-option').forEach(btn=>btn.addEventListener('click',()=>{$$('.gc-route-option').forEach(b=>b.classList.remove('is-selected'));btn.classList.add('is-selected');const origin=btn.dataset.origin||'China',dest=btn.dataset.dest||'Erbil';const f=$('#gcQuote');if(f){const o=f.querySelector('[name="origin"]');const d=f.querySelector('[name="destination"]');if(o)o.value=origin==='China + Dubai'?'china-dubai':origin.toLowerCase()==='dubai'?'dubai':'china';if(d)d.value=`${dest}, Iraq`;}}));}
  async function track(){const input=$('#gcTracking'),stateEl=$('#gcTrackState'),card=$('#gcShipment'),id=input.value.trim();if(!id){stateEl.textContent=state.lang==='ku'?'ژمارەی شوێنکەوتن بنووسە.':'Enter a tracking number.';return;}stateEl.textContent=state.lang==='ku'?'لە Supabase production دەگەڕێم...':'Checking the production Supabase service…';try{const r=await fetch(`${SUPA}/functions/v1/public-track?id=${encodeURIComponent(id)}`,{headers:{apikey:KEY,Accept:'application/json'},cache:'no-store'}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);const s=data.shipment||data.data||{};const origin=s.origin_key||s.origin||'—',dest=s.dest_key||s.dest_key||s.destination||'—',status=s.status||s.state||'—',track=s.tracking_number||s.id||id;card.className='gc-shipment loaded';card.innerHTML=`<div><div style="display:flex;justify-content:space-between;gap:12px;align-items:start"><div><strong>${safe(track)}</strong><div style="color:#9eb3c8;font-size:11px;margin-top:3px">${safe(origin)} → ${safe(dest)}</div></div><span class="gc-status">${safe(status)}</span></div><div class="gc-data"><div><small>${state.lang==='ku'?'سەرەتا':'Origin'}</small><b>${safe(origin)}</b></div><div><small>${state.lang==='ku'?'مەبەست':'Destination'}</small><b>${safe(dest)}</b></div><div><small>${state.lang==='ku'?'دۆخی نوێ':'Status'}</small><b>${safe(status)}</b></div><div><small>${state.lang==='ku'?'سێرڤەر':'Backend'}</small><b>Supabase</b></div></div></div>`;stateEl.textContent=state.lang==='ku'?'بارەکە دۆزرایەوە.':'Shipment loaded successfully.';}catch(e){card.className='gc-shipment gc-empty';card.innerHTML=`<div class="gc-empty-icon">!</div><div><strong>${state.lang==='ku'?'بارەکە نەدۆزرایەوە':'Shipment not found'}</strong><span>${safe(e.message)}</span></div>`;stateEl.textContent=state.lang==='ku'?'ژمارەکە دوبارە بپشکنە.':'Check the tracking number and try again.';}}
  async function quote(ev){ev.preventDefault();const f=ev.currentTarget,result=$('#gcQuoteResult'),d=new FormData(f);const msg=[`Route: ${d.get('origin')} → ${d.get('destination')}`,`Mode: ${d.get('mode')}`,`Details: ${d.get('message')}`].join('\n');const payload={name:d.get('name'),email:d.get('email'),message:msg,company:'Global Cloud website',request_type:'shipping',company_website:d.get('company_website')};result.textContent=state.lang==='ku'?'لە production دەنێردرێت...':'Sending to production server…';try{const r=await fetch(`${SUPA}/functions/v1/public-message`,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY},body:JSON.stringify(payload)}),body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`HTTP ${r.status}`);result.textContent=state.lang==='ku'?'داواکارییەکەت نێردرا.':'Request sent successfully.';f.reset();}catch(e){result.textContent=state.lang==='ku'?'ناردن سەرکەوتوو نەبوو.':'The request could not be sent.';}}
  function wire(){applyLang();applyTheme();initMenu();initRoutes();initMap();$('#gcLang')?.addEventListener('click',()=>{state.lang=state.lang==='ku'?'en':'ku';applyLang();});$('#gcTheme')?.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();});$('#gcTrackBtn')?.addEventListener('click',track);$('#gcTracking')?.addEventListener('keydown',e=>{if(e.key==='Enter')track();});$('#gcQuote')?.addEventListener('submit',quote);}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',wire):wire();
})();
