(() => {
  'use strict';
  const state={lang:localStorage.getItem('gc-lang')==='en'?'en':'ku',route:'china',theme:localStorage.getItem('gc-theme')||'dark',trackingId:''};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function applyLang(){document.documentElement.lang=state.lang==='ku'?'ckb':'en';document.documentElement.dir=state.lang==='ku'?'rtl':'ltr';localStorage.setItem('gc-lang',state.lang);$$('[data-ku]').forEach(e=>e.textContent=e.dataset[state.lang]);}
  function applyTheme(){document.documentElement.dataset.theme=state.theme;localStorage.setItem('gc-theme',state.theme);}
  function initMenu(){const btn=$('#gcMenu'),panel=$('#gcMenuPanel');btn?.addEventListener('click',()=>{panel.hidden=!panel.hidden});$$('#gcMenuPanel a').forEach(a=>a.addEventListener('click',()=>{panel.hidden=true;}));}
  function initMap(){const el=$('#gcMap');if(!el||el.dataset.ready)return;if(!window.L){el.innerHTML='<div class="gc-map-error">Map service unavailable.</div>';return;}const map=L.map(el,{scrollWheelZoom:false,zoomControl:true}).setView([28,58],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);const hubs=[{name:'Guangzhou · China',coords:[23.1291,113.2644],flag:'🇨🇳'},{name:'Dubai · UAE',coords:[25.2048,55.2708],flag:'🇦🇪'},{name:'Erbil · Iraq',coords:[36.1911,44.0092],flag:'🇮🇶'}];const pin=emoji=>L.divIcon({className:'gc-pin',html:`<div>${emoji}</div>`,iconSize:[38,38],iconAnchor:[19,19]});hubs.forEach(h=>L.marker(h.coords,{icon:pin(h.flag)}).addTo(map).bindPopup(`<b>${safe(h.name)}</b>`));L.polyline(hubs.map(h=>h.coords),{color:'#29d7e8',weight:3,opacity:.85,dashArray:'8 8'}).addTo(map);map.fitBounds(L.latLngBounds(hubs.map(h=>h.coords)).pad(.2));el.dataset.ready='1';window.gcMap=map;setTimeout(()=>map.invalidateSize(),150);}
  function initRoutes(){$$('.gc-route-option').forEach(btn=>btn.addEventListener('click',()=>{$$('.gc-route-option').forEach(b=>b.classList.remove('is-selected'));btn.classList.add('is-selected');const origin=btn.dataset.origin||'China',dest=btn.dataset.dest||'Erbil',f=$('#gcQuote');if(f){const o=f.querySelector('[name="origin"]'),d=f.querySelector('[name="destination"]');if(o)o.value=origin==='China + Dubai'?'china-dubai':origin.toLowerCase()==='dubai'?'dubai':'china';if(d)d.value=`${dest}, Iraq`;}}));}
  async function health(){const badge=$('#gcBackendStatus');if(!badge)return;try{const r=await fetch('/api/health',{cache:'no-store'}),d=await r.json();badge.className=`gc-backend ${d.ok?'online':'degraded'}`;badge.querySelector('b').textContent=d.ok?(state.lang==='ku'?'سێرڤەر کارە':'SERVER ONLINE'):(state.lang==='ku'?'سێرڤەر کێشەی هەیە':'SERVER DEGRADED');badge.querySelector('small').textContent=d.ok?`${d.latency_ms}ms · ${state.lang==='ku'?'داتابەیس':'database'}`:(d.error||'Unavailable');}catch{badge.className='gc-backend offline';badge.querySelector('b').textContent=state.lang==='ku'?'سێرڤەر بەردەست نییە':'SERVER OFFLINE';badge.querySelector('small').textContent=state.lang==='ku'?'پەیوەندی API نەکرا':'API unavailable';}}
  async function track(silent=false){const input=$('#gcTracking'),stateEl=$('#gcTrackState'),card=$('#gcShipment'),id=input?.value.trim();if(!id){if(!silent)stateEl.textContent=state.lang==='ku'?'ژمارەی شوێنکەوتن بنووسە.':'Enter a tracking number.';return;}state.trackingId=id;if(!silent)stateEl.textContent=state.lang==='ku'?'لە سێرڤەری production دەگەڕێم...':'Checking the production server…';try{const r=await fetch(`/api/track?id=${encodeURIComponent(id)}`,{cache:'no-store',headers:{Accept:'application/json'}}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);const s=data.shipment||data.data||{};const origin=s.origin_key||s.origin||'—',dest=s.dest_key||s.destination||'—',status=s.operational_status||s.status||s.state||'—',trackId=s.tracking_number||s.id||id,updated=s.tracking_updated_at||s.updated_at||'';card.className='gc-shipment loaded';card.innerHTML=`<div><div class="gc-shipment-head"><div><strong>${safe(trackId)}</strong><div class="gc-route-label">${safe(origin)} → ${safe(dest)}</div></div><span class="gc-status">${safe(status)}</span></div><div class="gc-data"><div><small>${state.lang==='ku'?'سەرەتا':'Origin'}</small><b>${safe(origin)}</b></div><div><small>${state.lang==='ku'?'مەبەست':'Destination'}</small><b>${safe(dest)}</b></div><div><small>${state.lang==='ku'?'دۆخ':'Status'}</small><b>${safe(status)}</b></div><div><small>${state.lang==='ku'?'نوێکراوەتەوە':'Updated'}</small><b>${safe(updated?new Date(updated).toLocaleString(): '—')}</b></div></div></div>`;stateEl.textContent=state.lang==='ku'?'بارەکە لە داتابەیسی واقعی دۆزرایەوە.':'Live shipment loaded from production database.';}catch(e){if(!silent){card.className='gc-shipment gc-empty';card.innerHTML=`<div class="gc-empty-icon">!</div><div><strong>${state.lang==='ku'?'بارەکە نەدۆزرایەوە':'Shipment not found'}</strong><span>${safe(e.message)}</span></div>`;stateEl.textContent=state.lang==='ku'?'پشکنینی ژمارەکە سەرکەوتوو نەبوو.':'Production tracking request failed.';}}}
  async function quote(ev){ev.preventDefault();const f=ev.currentTarget,result=$('#gcQuoteResult'),d=new FormData(f),payload={name:d.get('name'),phone:d.get('phone'),origin:d.get('origin'),destination:d.get('destination'),mode:d.get('mode'),weight_kg:d.get('weight_kg'),volume_cbm:d.get('volume_cbm'),items_count:d.get('items_count'),message:d.get('message')};if(!payload.name||!payload.origin||!payload.destination||!payload.mode){result.textContent=state.lang==='ku'?'تکایە خانە پێویستەکان پڕ بکەرەوە.':'Please complete the required fields.';return;}result.textContent=state.lang==='ku'?'لە سێرڤەری واقعی دەنێردرێت...':'Sending to production API…';try{const r=await fetch('/api/quote',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload),cache:'no-store'}),body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`HTTP ${r.status}`);result.textContent=state.lang==='ku'?'داواکارییەکەت بە سەرکەوتوویی تۆمار کرا.':'Quote request saved to production.';f.reset();health();}catch(e){result.textContent=state.lang==='ku'?`ناردن سەرکەوتوو نەبوو: ${e.message}`:`Request failed: ${e.message}`;}}
  function wire(){applyLang();applyTheme();initMenu();initRoutes();initMap();health();setInterval(health,30000);$('#gcLang')?.addEventListener('click',()=>{state.lang=state.lang==='ku'?'en':'ku';applyLang();health();});$('#gcTheme')?.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();});$('#gcTrackBtn')?.addEventListener('click',()=>track(false));$('#gcTracking')?.addEventListener('keydown',e=>{if(e.key==='Enter')track(false);});$('#gcQuote')?.addEventListener('submit',quote);setInterval(()=>{if(state.trackingId&&document.visibilityState==='visible')track(true);},30000);}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',wire):wire();
})();
