/* Globall Cloud — production integration bridge
 * Keeps the public page and internal staff surfaces on one verified
 * Supabase client/config without exposing service-role credentials.
 */
(() => {
  'use strict';
  const SUPABASE_URL = 'https://ahslifnthiwfkmaswjno.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_M4UtzEbCLwMCd9LanFWw5g_5b7-fWda';
  const CDN = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js';
  const PUBLIC_CONFIG = `${SUPABASE_URL}/functions/v1/public-config?key=usd_iqd_rate`;
  const DISCORD_FUNCTION = `${SUPABASE_URL}/functions/v1/discord-notify`;
  const DISCORD_SERVER_ID = '1540898219075043388';
  const LEGACY_MESSAGE = 'Supabase هێشتا پەیوەست نەکراوە';
  const READY_MESSAGE = 'Supabase بە سەرکەوتوویی پەیوەستە و سیستەمەکە ئامادەیە.';
  const LOADING_MESSAGE = 'پەیوەندیی پارێزراو بە Supabase لە پڕۆسەی پشکنینە.';
  const DISCORD_ACTIONS = new Set(['transition_shipment','upsert_package','upsert_customs','upsert_consolidation','attach_package','upsert_invoice','record_payment','resolve_exception','approve_quote','record_warehouse_movement','upsert_route_leg','register_document','upload_document']);
  const ready = () => Boolean(window.supabase && typeof window.supabase.createClient === 'function');
  const setHealthState = (state, detail = '') => { window.gcSupabaseHealth = { state, detail, checkedAt: new Date().toISOString() }; window.dispatchEvent(new CustomEvent('gc:supabase-health', { detail: window.gcSupabaseHealth })); };
  const updateConnectionMessage = (connected) => { document.querySelectorAll('[data-gc-supabase-status]').forEach((node) => { node.textContent = connected ? 'Supabase connected' : 'Connecting to Supabase…'; node.dataset.state = connected ? 'ready' : 'loading'; }); document.querySelectorAll('*').forEach((node) => { if (node.children.length) return; if ((node.textContent || '').trim() === LEGACY_MESSAGE) { node.textContent = connected ? READY_MESSAGE : LOADING_MESSAGE; node.setAttribute('data-gc-connection-message', connected ? 'ready' : 'loading'); } }); };
  const discordTitle = (action, data) => { const titles = { transition_shipment:'Shipment status updated',upsert_package:'Shipment package updated',upsert_customs:'Customs case updated',upsert_consolidation:'Consolidation batch updated',attach_package:'Package attached to consolidation',upsert_invoice:'Invoice updated',record_payment:'Payment recorded',resolve_exception:'Logistics exception resolved',approve_quote:'Quote approved',record_warehouse_movement:'Warehouse movement recorded',upsert_route_leg:'Shipment route leg updated',register_document:'Shipment document registered',upload_document:'Shipment document uploaded' }; const shipmentId = data?.shipment_id || ''; return shipmentId ? `${titles[action] || 'Globall Cloud update'} • ${shipmentId}` : (titles[action] || 'Globall Cloud update'); };
  const discordRoute = (data) => { if (data?.from_hub && data?.to_hub) return `${data.from_hub} → ${data.to_hub}`; if (data?.origin_hub && data?.destination_hub) return `${data.origin_hub} → ${data.destination_hub}`; if (data?.origin && data?.destination) return `${data.origin} → ${data.destination}`; return null; };
  const discordSeverity = (action, data) => { const status = String(data?.to_status || data?.status || '').toLowerCase(); if (status === 'exception' || status === 'on_hold' || action === 'resolve_exception') return 'high'; if (action === 'record_payment' || action === 'approve_quote') return 'success'; return 'info'; };
  const notifyDiscordForControlPlane = async (action, data, resultBody) => { if (!DISCORD_ACTIONS.has(action) || !window.gcSupabase) return; try { const sessionResult = await window.gcSupabase.auth.getSession(); const accessToken = sessionResult?.data?.session?.access_token; if (!accessToken) return; const dedupeBase = JSON.stringify({ action, data: data || {}, result: resultBody?.item?.id || resultBody?.item?.shipment_id || null }); const key = `gc-discord:${action}:${btoa(unescape(encodeURIComponent(dedupeBase))).slice(0, 180)}`; const previous = Number(sessionStorage.getItem(key) || 0); if (previous && Date.now() - previous < 5 * 60 * 1000) return; sessionStorage.setItem(key, String(Date.now())); const shipmentItem = resultBody?.item && typeof resultBody.item === 'object' ? resultBody.item : {}; const payload = { action:'send', server_id:DISCORD_SERVER_ID, event_type:action, title:discordTitle(action,data), shipment_id:data?.shipment_id || shipmentItem?.shipment_id || shipmentItem?.id || null, status:data?.to_status || data?.status || shipmentItem?.operational_status || null, route:discordRoute(data), severity:discordSeverity(action,data), details:[data?.package_code?`Package: ${data.package_code}`:null,data?.invoice_number?`Invoice: ${data.invoice_number}`:null,data?.batch_code?`Batch: ${data.batch_code}`:null,data?.document_type?`Document: ${data.document_type}`:null,data?.movement_type?`Movement: ${data.movement_type}`:null].filter(Boolean).join(' • ') || null }; const response = await fetch(DISCORD_FUNCTION,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'}); if(!response.ok) console.warn('[Globall Cloud] Discord bridge:',response.status); } catch(error){ console.warn('[Globall Cloud] Discord bridge:',error); } };
  const installDiscordBridge = () => { if(window.__gcDiscordBridgeInstalled)return; window.__gcDiscordBridgeInstalled=true; const nativeFetch=window.fetch.bind(window); window.fetch=async(input,init={})=>{const requestUrl=typeof input==='string'?input:input?.url||'';const method=String(init?.method||(typeof input!=='string'&&input?.method)||'GET').toUpperCase();const isControlPlane=requestUrl.includes('/functions/v1/logistics-control-plane');const bodyText=typeof init?.body==='string'?init.body:null;let requestBody=null;let action=null;if(isControlPlane&&method==='POST'&&bodyText){try{requestBody=JSON.parse(bodyText);action=String(requestBody?.action||'')}catch{requestBody=null}}const response=await nativeFetch(input,init);if(isControlPlane&&method==='POST'&&action&&DISCORD_ACTIONS.has(action)&&response.ok){try{const cloned=response.clone();const body=await cloned.json();void notifyDiscordForControlPlane(action,requestBody?.data||requestBody||{},body)}catch{}}return response;}; };
  const hideLegacyNoticeImmediately=()=>{const notice=document.getElementById('adminNotConfigured');if(notice){notice.hidden=true;notice.dataset.gcRuntimeState='checking';notice.setAttribute('aria-live','polite');}};
  const loadClientLibrary=()=>new Promise((resolve,reject)=>{if(ready())return resolve();const existing=document.querySelector('script[data-gc-supabase-loader]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return;}const script=document.createElement('script');script.src=CDN;script.async=true;script.dataset.gcSupabaseLoader='1';script.onload=resolve;script.onerror=()=>reject(new Error('Supabase client library failed to load'));document.head.appendChild(script);});
  const ensureClient=async()=>{await loadClientLibrary();if(!window.gcSupabase){window.gcSupabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true},global:{headers:{'x-gc-client':'web-production'}}});}window.sb=window.gcSupabase;window.gcSupabaseConfig={url:SUPABASE_URL,publishableKey:SUPABASE_PUBLISHABLE_KEY,publishableKeyPresent:Boolean(SUPABASE_PUBLISHABLE_KEY)};window.dispatchEvent(new CustomEvent('gc:supabase-ready',{detail:{client:window.gcSupabase}}));installDiscordBridge();return window.gcSupabase;};
  const verifyPublicConnection=async()=>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),5000);setHealthState('checking');try{const response=await fetch(PUBLIC_CONFIG,{method:'GET',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Accept:'application/json'},signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error(`Supabase public-config health ${response.status}`);const body=await response.json();if(!body||body.key!=='usd_iqd_rate'||body.value===null||body.value===undefined)throw new Error('Supabase public-config returned an invalid payload');setHealthState('ready');updateConnectionMessage(true);return true;}catch(error){const detail=String(error?.message||error);setHealthState('degraded',detail);throw error;}finally{clearTimeout(timeout);}};
  const boot=async()=>{hideLegacyNoticeImmediately();setHealthState('checking');updateConnectionMessage(false);try{await ensureClient();await verifyPublicConnection();}catch(error){console.error('[Globall Cloud] Production bridge:',error);window.gcSupabaseError=String(error?.message||error);updateConnectionMessage(false);}};
  window.gcEnsureSupabase=ensureClient;window.gcVerifySupabaseHealth=verifyPublicConnection;window.gcDiscordNotify=notifyDiscordForControlPlane;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else void boot();
})();
