import { createClient } from 'npm:@supabase/supabase-js@2'
type Json = Record<string, unknown>
type OutboxItem={id:string;customer_user_id:string|null;shipment_id:string|null;channel:string;event_key:string;recipient:string|null;payload:Json;attempts?:number}
type DeliveryReceipt={provider:'resend'|'gmail'|'whatsapp'|'twilio';providerMessageId?:string|null;providerStatus?:string|null}
const json=(body:Json,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})
const serviceClient=()=>{const url=Deno.env.get('SUPABASE_URL');const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY');if(!url||!key)throw new Error('Supabase service configuration is unavailable');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})}
const payloadText=(item:OutboxItem)=>String(item.payload?.body||item.payload?.text||item.payload?.note||'Your Globall Cloud shipment has a new update.').slice(0,4000)
const payloadTitle=(item:OutboxItem)=>String(item.payload?.title||item.payload?.subject||'Globall Cloud shipment update').slice(0,180)
const responseBody=async(r:Response)=>await r.json().catch(()=>({})) as Json
const responseError=async(provider:string,r:Response)=>{const b=await responseBody(r);const m=b.error&&typeof b.error==='object'?(b.error as Json).message:b.message;return new Error(`${provider} provider returned ${r.status}${m?`: ${String(m).slice(0,180)}`:''}`)}
const base64Url=(v:string)=>btoa(v).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')
const gmailAccessToken=async()=>{const clientId=Deno.env.get('GOOGLE_CLIENT_ID'),clientSecret=Deno.env.get('GOOGLE_CLIENT_SECRET'),refreshToken=Deno.env.get('GOOGLE_REFRESH_TOKEN');if(!clientId||!clientSecret||!refreshToken)throw new Error('Gmail provider is not configured');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:refreshToken,grant_type:'refresh_token'})});const b=await r.json();if(!r.ok||!b.access_token)throw new Error(`Gmail OAuth returned ${r.status}`);return String(b.access_token)}
const deliverResend=async(item:OutboxItem):Promise<DeliveryReceipt>=>{const apiKey=Deno.env.get('RESEND_API_KEY'),from=Deno.env.get('RESEND_FROM_EMAIL');if(!apiKey||!from)throw new Error('Resend provider is not configured');if(!item.recipient)throw new Error('Email recipient is missing');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','Idempotency-Key':`globall-cloud-${item.id}`},body:JSON.stringify({from,to:[item.recipient],subject:payloadTitle(item),text:payloadText(item)})});if(!r.ok)throw await responseError('Resend',r);const b=await responseBody(r);return{provider:'resend',providerMessageId:String(b.id||''),providerStatus:'sent'}}
const deliverGmail=async(item:OutboxItem):Promise<DeliveryReceipt>=>{const from=Deno.env.get('GOOGLE_SENDER_EMAIL');if(!from)throw new Error('Gmail sender is not configured');if(!item.recipient)throw new Error('Email recipient is missing');const mime=[`From: ${from}`,`To: ${item.recipient}`,`Subject: ${payloadTitle(item)}`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','',payloadText(item)].join('\r\n');const r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{Authorization:`Bearer ${await gmailAccessToken()}`,'Content-Type':'application/json'},body:JSON.stringify({raw:base64Url(mime)})});if(!r.ok)throw await responseError('Gmail',r);const b=await responseBody(r);return{provider:'gmail',providerMessageId:String(b.id||b.threadId||''),providerStatus:'sent'}}
const deliverEmail=async(item:OutboxItem)=>Deno.env.get('RESEND_API_KEY')&&Deno.env.get('RESEND_FROM_EMAIL')?deliverResend(item):deliverGmail(item)
const deliverWhatsApp=async(item:OutboxItem):Promise<DeliveryReceipt>=>{const token=Deno.env.get('META_ACCESS_TOKEN')||Deno.env.get('WHATSAPP_ACCESS_TOKEN');const phoneNumberId=Deno.env.get('META_PHONE_NUMBER_ID')||Deno.env.get('WHATSAPP_PHONE_NUMBER_ID');const templateName=String(item.payload?.template_name||Deno.env.get('WHATSAPP_TEMPLATE_NAME')||'globall_notification');const language=String(item.payload?.template_language||Deno.env.get('WHATSAPP_TEMPLATE_LANGUAGE')||'en_US');if(!token||!phoneNumberId)throw new Error('WhatsApp provider is not configured');if(!item.recipient)throw new Error('WhatsApp recipient is missing');const media=item.payload?.media_url?String(item.payload.media_url):null;const components:any[]=[];if(media)components.push({type:'header',parameters:[{type:'image',image:{link:media}}]});components.push({type:'body',parameters:[{type:'text',text:payloadText(item).slice(0,1024)}]});const r=await fetch(`https://graph.facebook.com/v23.0/${encodeURIComponent(phoneNumberId)}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','Idempotency-Key':`globall-cloud-${item.id}`},body:JSON.stringify({messaging_product:'whatsapp',to:item.recipient,type:'template',template:{name:templateName,language:{code:language},components}})});if(!r.ok)throw await responseError('WhatsApp',r);const b=await responseBody(r);const id=Array.isArray(b.messages)&&b.messages[0]&&typeof b.messages[0]==='object'?String((b.messages[0] as Json).id||''):'';return{provider:'whatsapp',providerMessageId:id,providerStatus:'accepted'}}
const deliverSms=async(item:OutboxItem):Promise<DeliveryReceipt>=>{const sid=Deno.env.get('TWILIO_ACCOUNT_SID'),token=Deno.env.get('TWILIO_AUTH_TOKEN'),from=Deno.env.get('TWILIO_FROM_NUMBER');if(!sid||!token||!from)throw new Error('SMS provider is not configured');if(!item.recipient)throw new Error('SMS recipient is missing');const params:Record<string,string>={To:item.recipient,From:from,Body:`${payloadTitle(item)}: ${payloadText(item)}`};const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(sid)}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${btoa(`${sid}:${token}`)}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});if(!r.ok)throw await responseError('Twilio',r);const b=await responseBody(r);return{provider:'twilio',providerMessageId:String(b.sid||''),providerStatus:String(b.status||'accepted')}}
const deliverInApp=async(service:ReturnType<typeof serviceClient>,item:OutboxItem):Promise<DeliveryReceipt>=>{if(!item.customer_user_id)throw new Error('In-app notification customer is missing');const result=await service.from('customer_notifications').insert({customer_user_id:item.customer_user_id,shipment_id:item.shipment_id,kind:item.event_key,title:payloadTitle(item),body:payloadText(item),action_url:String(item.payload?.action_url||(item.shipment_id?`/?track=${encodeURIComponent(item.shipment_id)}`:'/customer-portal.html'))});if(result.error)throw result.error;return{provider:'gmail',providerStatus:'sent'}}
const deliver=async(service:ReturnType<typeof serviceClient>,item:OutboxItem):Promise<DeliveryReceipt>=>{if(item.channel==='in_app')return deliverInApp(service,item);if(item.channel==='email')return deliverEmail(item);if(item.channel==='whatsapp')return deliverWhatsApp(item);if(item.channel==='sms')return deliverSms(item);throw new Error(`Unsupported notification channel: ${item.channel}`)}
const saveReceipt=async(service:ReturnType<typeof serviceClient>,item:OutboxItem,receipt:DeliveryReceipt)=>{const r=await service.from('notification_outbox').update({provider_message_id:receipt.providerMessageId||null,provider_status:receipt.providerStatus||'accepted',updated_at:new Date().toISOString()}).eq('id',item.id);if(r.error)throw r.error}
Deno.serve(async req=>{if(req.method!=='POST')return json({error:'Method not allowed'},405);const secret=Deno.env.get('NOTIFICATION_WORKER_SECRET');if(!secret||req.headers.get('x-notification-worker-secret')!==secret)return json({error:'Unauthorized'},401);try{const body=await req.json().catch(()=>({})) as Json;const limit=Math.min(100,Math.max(1,Number(body.limit||25)));const service=serviceClient();const claimed=await service.rpc('claim_notification_outbox_external',{p_limit:limit});if(claimed.error)throw claimed.error;const results:Json[]=[];for(const item of (claimed.data||[]) as OutboxItem[]){try{const receipt=await deliver(service,item);await saveReceipt(service,item,receipt);const done=await service.rpc('complete_notification_outbox',{p_id:item.id,p_success:true,p_error:null});if(done.error)throw done.error;results.push({id:item.id,channel:item.channel,status:'sent',provider:receipt.provider,provider_message_id:receipt.providerMessageId||null})}catch(e){const message=e instanceof Error?e.message:'Notification delivery failed';await service.rpc('complete_notification_outbox',{p_id:item.id,p_success:false,p_error:message});results.push({id:item.id,channel:item.channel,status:'retryable',error:message.slice(0,240)})}}return json({claimed:results.length,results})}catch(e){return json({error:e instanceof Error?e.message:'Internal server error'},500)}})
