import { createClient } from 'npm:@supabase/supabase-js@2'
const ORIGINS=new Set(['https://globall-cloud.pages.dev','https://globall-cloud.netlify.app'])
const BUCKET='warehouse-receipts'
const TTL=60*60
const cors=(req:Request)=>({'Access-Control-Allow-Origin':ORIGINS.has(req.headers.get('origin')||'')?req.headers.get('origin')!:'https://globall-cloud.pages.dev','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info, x-supabase-auth-token','Access-Control-Allow-Methods':'POST,OPTIONS','Cache-Control':'no-store','Vary':'Origin'})
const json=(req:Request,b:unknown,status=200)=>new Response(JSON.stringify(b),{status,headers:{'Content-Type':'application/json; charset=utf-8',...cors(req)}})
const txt=(v:unknown)=>{const s=String(v??'').trim();return s||null}
function path(v:unknown){const s=txt(v);if(!s)return null;if(!s.startsWith('http'))return s.replace(/^\/+/, '');const marker=`/storage/v1/object/sign/${BUCKET}/`;const i=s.indexOf(marker);return i>=0?decodeURIComponent(s.slice(i+marker.length).split('?')[0]):null}
async function actor(req:Request){const auth=req.headers.get('authorization')||'';if(!/^Bearer\s+/i.test(auth))throw new Error('Unauthorized');const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const ac=createClient(url,anon,{auth:{persistSession:false},global:{headers:{Authorization:auth}}});const{data,error}=await ac.auth.getUser();if(error||!data.user)throw new Error('Unauthorized');const admin=createClient(url,service,{auth:{persistSession:false}});const{data:staff}=await admin.from('staff').select('id,full_name,role,is_active').eq('id',data.user.id).maybeSingle();if(!staff?.is_active)throw new Error('Forbidden');if(!['admin','super_admin','accountant','warehouse','warehouse_china','warehouse_uae','warehouse_erbil','operations','delivery'].includes(String(staff.role)))throw new Error('Forbidden');return{admin,staff,user:data.user}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors(req)});if(req.method!=='POST')return json(req,{error:'Method not allowed'},405);try{const a=await actor(req);const body=await req.json().catch(()=>({})) as Record<string,unknown>;const receiptId=txt(body.receipt_id);if(!receiptId)throw new Error('receipt_id is required');const{data:receipt,error:re}=await a.admin.from('warehouse_receipts').select('id,gc_code,batch_code,location,carton_count,received_at,photos,shipment_id,directory_customer_id,label_metadata,notes').or(`id.eq.${receiptId}`).maybeSingle();if(re)throw re;if(!receipt)throw new Error('Receipt not found');const{data:customer,error:ce}=await a.admin.from('customer_directory').select('id,gc_code,code,name,phone,phone2,email,auth_user_id,is_active').eq('id',receipt.directory_customer_id).maybeSingle();if(ce)throw ce;if(!customer)throw new Error('Customer not found');const rawPhotos=Array.isArray(receipt.photos)?receipt.photos:[];const paths=rawPhotos.map(path).filter((x):x is string=>Boolean(x));const{data:signed,error:se}=paths.length?await a.admin.storage.from(BUCKET).createSignedUrls(paths,TTL):{data:[],error:null};if(se)throw se;const photoUrls=(signed||[]).map(x=>x.signedUrl).filter((x):x is string=>Boolean(x));const cartons=Number(receipt.carton_count??receipt.label_metadata?.total_packages??0)||0;const warehouse=String(receipt.location||'warehouse');const gc=String(customer.gc_code||customer.code||receipt.gc_code||'');const customerName=String(customer.name||'کڕیار');const bodyText=`سڵاو ${customerName}، ${cartons||'چەند'} کارتۆن/بەش لە کاڵاکانت لە کۆگای ${warehouse} وەرگیراوە. GC: ${gc}. بەروار: ${new Intl.DateTimeFormat('ku-IQ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(receipt.received_at||Date.now()))}.`;
if(customer.auth_user_id){const {error}=await a.admin.from('customer_notifications').insert({customer_user_id:customer.auth_user_id,shipment_id:receipt.shipment_id||null,kind:'warehouse_received',event_key:`warehouse_received:${receipt.id}`,title:'کاڵاکەت لە کۆگا وەرگیرا',body:bodyText,action_url:`/track?gc=${encodeURIComponent(gc)}`});if(error)throw error}
const already=await a.admin.from('notification_outbox').select('id').eq('event_key',`warehouse_received:${receipt.id}`).eq('channel','whatsapp').limit(1);if(!already.error&&!already.data?.length&& (customer.phone||customer.phone2)){await a.admin.from('notification_outbox').insert({customer_user_id:customer.auth_user_id||null,shipment_id:receipt.shipment_id||null,channel:'whatsapp',event_key:`warehouse_received:${receipt.id}`,recipient:customer.phone||customer.phone2,payload:{title:'کاڵاکەت لە کۆگا وەرگیرا',body:bodyText,template_name:Deno.env.get('WHATSAPP_TEMPLATE_NAME')||'globall_warehouse_received',template_language:Deno.env.get('WHATSAPP_TEMPLATE_LANGUAGE')||'ckb',media_url:photoUrls[0]||null,action_url:`/track?gc=${encodeURIComponent(gc)}`,gc_code:gc,warehouse,carton_count:cartons,photo_count:photoUrls.length}})}
if(customer.email){const check=await a.admin.from('notification_outbox').select('id').eq('event_key',`warehouse_received:${receipt.id}`).eq('channel','email').limit(1);if(!check.error&&!check.data?.length){await a.admin.from('notification_outbox').insert({customer_user_id:customer.auth_user_id||null,shipment_id:receipt.shipment_id||null,channel:'email',event_key:`warehouse_received:${receipt.id}`,recipient:customer.email,payload:{title:'کاڵاکەت لە کۆگا وەرگیرا',body:bodyText,gc_code:gc,warehouse,carton_count:cartons,photo_count:photoUrls.length,action_url:`/track?gc=${encodeURIComponent(gc)}`}})}}
await a.admin.from('staff_activity_log').insert({staff_id:a.staff.id,staff_name:a.staff.full_name,action:'warehouse.notification_queued',target_id:String(receipt.id),details:JSON.stringify({gc_code:gc,warehouse,cartons,photos:photoUrls.length})});return json(req,{ok:true,receipt_id:receipt.id,gc_code:gc,notification:{in_app:Boolean(customer.auth_user_id),whatsapp_queued:Boolean(customer.phone||customer.phone2),email_queued:Boolean(customer.email),photos:photoUrls.length}})}catch(e){const m=e instanceof Error?e.message:String(e);const s=/Unauthorized/i.test(m)?401:/Forbidden/i.test(m)?403:/required|not found/i.test(m)?400:500;return json(req,{error:m},s)}})
