import { createClient } from 'npm:@supabase/supabase-js@2'
const ORIGINS=new Set(['https://globall-cloud.pages.dev','https://globall-cloud.netlify.app'])
const STAFF=new Set(['super_admin','admin','accountant'])
const cors=(req:Request)=>({'Access-Control-Allow-Origin':ORIGINS.has(req.headers.get('origin')||'')?req.headers.get('origin')!:'https://globall-cloud.pages.dev','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info, x-supabase-auth-token, x-fx-worker-secret','Access-Control-Allow-Methods':'POST,OPTIONS','Cache-Control':'no-store','Vary':'Origin'})
const json=(req:Request,b:Record<string,unknown>,status=200)=>new Response(JSON.stringify(b),{status,headers:{'Content-Type':'application/json; charset=utf-8',...cors(req)}})
const text=(v:unknown)=>v==null?'':String(v).trim()
const env=(name:string)=>{const v=Deno.env.get(name);if(!v)throw new Error(`${name} is not configured`);return v}
const errorText=(e:unknown)=>e instanceof Error?e.message: (()=>{try{return JSON.stringify(e)}catch{return String(e)}})()
async function dbClient(){const url=env('SUPABASE_URL');const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY');if(!service)throw new Error('Supabase service key is not configured');return createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})}
async function workerAuthorized(req:Request,db:ReturnType<typeof createClient>){const provided=req.headers.get('x-fx-worker-secret')||'';if(!provided)return false;const {data,error}=await db.rpc('verify_fx_worker_secret',{p_secret:provided});return !error&&data===true}
async function staffAuthorized(req:Request,db:ReturnType<typeof createClient>){const url=env('SUPABASE_URL');const anon=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY');const authHeader=req.headers.get('Authorization')||'';if(!anon||!/^Bearer\s+/i.test(authHeader))return null;const ac=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{headers:{Authorization:authHeader}}});const {data,error}=await ac.auth.getUser();if(error||!data.user)return null;const {data:staff}=await db.from('staff').select('id,full_name,role,is_active').eq('id',data.user.id).maybeSingle();if(!staff?.is_active||!STAFF.has(String(staff.role)))return null;return staff}
async function fetchMarket(){const r=await fetch('https://open.er-api.com/v6/latest/USD',{headers:{Accept:'application/json','User-Agent':'Globall-Cloud-FX/1.0'},cache:'no-store'});if(!r.ok)throw new Error(`Market FX provider returned HTTP ${r.status}`);const d=await r.json();const rate=Number(d?.rates?.IQD);if(!Number.isFinite(rate)||rate<=0)throw new Error('Market FX provider returned no valid USD/IQD rate');return{rate,source:'open.er-api.com',provider_updated_at:d?.time_last_update_utc||null,next_update_at:d?.time_next_update_utc||null}}
async function fetchCBI(){const r=await fetch('https://api.frankfurter.dev/v2/rate/USD/IQD?providers=CBI',{headers:{Accept:'application/json','User-Agent':'Globall-Cloud-FX/1.0'},cache:'no-store'});if(!r.ok)throw new Error(`CBI FX provider returned HTTP ${r.status}`);const d=await r.json();const rate=Number(d?.rate);if(!Number.isFinite(rate)||rate<=0)throw new Error('CBI FX provider returned no valid USD/IQD rate');return{rate,source:'Frankfurter/CBI',provider_updated_at:d?.date||null,next_update_at:null}}
async function fetchRate(requested:string){const providers=requested==='cbi'?['cbi','market']:requested==='market'?['market','cbi']:['cbi','market'];const errors:string[]=[];for(const provider of providers){try{return provider==='cbi'?await fetchCBI():await fetchMarket()}catch(e){errors.push(`${provider}: ${errorText(e)}`)}}throw new Error(`All FX providers failed. ${errors.join(' | ')}`)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,{error:'Method not allowed'},405);try{const db=await dbClient();const worker=await workerAuthorized(req,db);const staff=worker?null:await staffAuthorized(req,db);if(!worker&&!staff)return json(req,{error:'Unauthorized'},401);const body=await req.json().catch(()=>({}));const requested=text(body.provider||'auto').toLowerCase();const apply=body.apply===true;const result=await fetchRate(requested);let row=null;if(apply){const {data,error}=await db.from('exchange_rates').insert({usd_to_iqd:result.rate,source:`auto:${result.source}`,effective_on:new Date().toISOString().slice(0,10)}).select('*').single();if(error)throw error;row=data;const audit=await db.from('staff_activity_log').insert({staff_id:staff?.id||null,staff_name:staff?.full_name||'FX worker',action:'exchange_rate.auto_update',target_id:String(data.id),details:JSON.stringify({usd_to_iqd:result.rate,source:result.source,provider_updated_at:result.provider_updated_at,worker})});if(audit.error)throw audit.error}return json(req,{ok:true,provider:result.source,rate:result.rate,source:result.source,provider_updated_at:result.provider_updated_at,next_update_at:result.next_update_at,applied:apply,row})}catch(e){const message=errorText(e);const status=/Unauthorized/i.test(message)?401:/permission/i.test(message)?403:/provider|valid|failed/i.test(message)?502:500;return json(req,{error:message},status)}})
