import { createClient } from 'npm:@supabase/supabase-js@2'

type Kind='customer'|'staff'|'receipt'|'log'|'shipment'
type Action='list'|'create'|'update'|'archive'|'delete'
type JsonRecord=Record<string,unknown>
const ALLOWED_ORIGINS=new Set(['https://globall-cloud.pages.dev','https://globall-cloud.netlify.app'])
function corsHeaders(req?:Request){const origin=req?.headers.get('origin')||'';return {'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://globall-cloud.pages.dev','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info, x-supabase-auth-token','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin','Cache-Control':'no-store'}}
function json(data:unknown,init:ResponseInit={},req?:Request){return new Response(JSON.stringify(data),{...init,headers:{'Content-Type':'application/json; charset=utf-8',...corsHeaders(req),...(init.headers??{})}})}
function responseError(message:string,status:number,req?:Request){return json({error:message},{status},req)}
function secretKey(){const direct=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(direct)return direct;return Deno.env.get('SUPABASE_SECRET_KEYS')||null}
function anonKey(){return Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||null}
function txt(value:unknown){if(value===null||value===undefined)return null;const str=String(value).trim();return str.length?str:null}
function normalizeKind(value:unknown):Kind{const kind=String(value||'customer').toLowerCase();if(kind==='staff'||kind==='receipt'||kind==='log'||kind==='shipment')return kind;return'customer'}
function normalizeAction(value:unknown):Action{const action=String(value||'list').toLowerCase();if(action==='create'||action==='update'||action==='archive'||action==='delete')return action;return'list'}
async function getActor(req:Request){const url=Deno.env.get('SUPABASE_URL');const anon=anonKey();const service=secretKey();if(!url||!anon||!service)throw new Error('Supabase server configuration is missing');const authHeader=req.headers.get('Authorization')||'';const authClient=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{headers:authHeader?{Authorization:authHeader}:{}}});const {data:userData,error:userErr}=await authClient.auth.getUser();if(userErr||!userData.user)throw responseError('Unauthorized',401,req);const serviceClient=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data:staffRow,error:staffErr}=await serviceClient.from('staff').select('id,full_name,role,branch,is_active').eq('id',userData.user.id).maybeSingle();if(staffErr)throw staffErr;if(!staffRow||staffRow.is_active!==true)throw responseError('Forbidden',403,req);const role=String(staffRow.role||'');return{serviceClient,staffRow,role,canRead:['admin','super_admin','accountant'].includes(role),canWrite:['admin','super_admin'].includes(role),isSuperAdmin:role==='super_admin'}}
async function logActivity(client:any,staffId:string,staffName:string|null,action:string,targetId:string|null,details:JsonRecord|null=null){try{await client.from('staff_activity_log').insert({staff_id:staffId,staff_name:staffName,action,target_id:targetId,details:details?JSON.stringify(details):null})}catch{}}
async function listCustomers(client:any){const {data,error}=await client.from('customer_directory').select('id,code,name,phone,phone2,email,city,delivery_location,note,auth_user_id,manager_staff_id,is_active,created_at,updated_at').order('created_at',{ascending:false});if(error)throw error;return{items:data??[],kind:'customer'}}
async function listShipments(client:any){const {data,error}=await client.from('shipments').select('id,created_at,total_amount,paid_amount,origin_key,dest_key,branch,customer_name,customer_phone,directory_customer_id,current_step_index,step_dates,eta,type,items_count,weight_kg,volume_cbm,operational_status,priority,assigned_staff_id,archived_at,batch_code,notes').order('created_at',{ascending:false}).limit(500);if(error)throw error;return{items:data??[],kind:'shipment'}}
async function listStaff(client:any){const {data,error}=await client.from('staff').select('id,full_name,role,branch,is_active,created_at,updated_at').order('created_at',{ascending:false});if(error)throw error;return{items:data??[],kind:'staff'}}
async function listReceipts(client:any){const {data,error}=await client.from('warehouse_receipts').select('id,batch_code,location,notes,received_at,created_by_name,directory_customer_id,directory_phone,consolidated,photos,created_at').order('received_at',{ascending:false}).limit(100);if(error)throw error;return{items:data??[],kind:'receipt'}}
async function listLogs(client:any){const {data,error}=await client.from('staff_activity_log').select('id,staff_id,staff_name,action,target_id,details,created_at').order('created_at',{ascending:false}).limit(100);if(error)throw error;return{items:data??[],kind:'log'}}
async function customerWrite(client:any,actor:any,action:Action,data:JsonRecord){if(!actor.isSuperAdmin)throw responseError('Only Super Admin can manage customer accounts',403);const id=txt(data.id);if(action==='update'){if(!id)throw responseError('Missing customer id',400);const updates:any={};for(const k of ['name','email','phone','phone2','city','delivery_location','note','manager_staff_id'])if(data[k]!==undefined)updates[k]=txt(data[k]);if(typeof data.is_active==='boolean')updates.is_active=data.is_active;const r=await client.from('customer_directory').update(updates).eq('id',id).select('*').single();if(r.error)throw r.error;await logActivity(client,actor.staffRow.id,actor.staffRow.full_name,'update_customer_account',id,updates);return r.data}if(action==='archive'||action==='delete'){if(!id)throw responseError('Missing customer id',400);const r=await client.from('customer_directory').update({is_active:false}).eq('id',id).select('*').single();if(r.error)throw r.error;await logActivity(client,actor.staffRow.id,actor.staffRow.full_name,'archive_customer_account',id);return r.data}if(action==='create'){const row={name:txt(data.name)||'Customer',email:txt(data.email),phone:txt(data.phone),phone2:txt(data.phone2),city:txt(data.city),delivery_location:txt(data.delivery_location),note:txt(data.note),manager_staff_id:txt(data.manager_staff_id),is_active:true,auth_user_id:txt(data.auth_user_id)};const r=await client.from('customer_directory').insert(row).select('*').single();if(r.error)throw r.error;await logActivity(client,actor.staffRow.id,actor.staffRow.full_name,'create_customer_account',String(r.data.id));return r.data}throw responseError('Unsupported customer action',400)}
async function staffWrite(client:any,actor:any,action:Action,data:JsonRecord){if(!actor.isSuperAdmin)throw responseError('Only Super Admin can manage staff accounts',403);const id=txt(data.id);if(action==='update'){if(!id)throw responseError('Missing staff id',400);const updates:any={};for(const k of ['full_name','role','branch'])if(data[k]!==undefined)updates[k]=txt(data[k]);if(typeof data.is_active==='boolean')updates.is_active=data.is_active;const r=await client.from('staff').update(updates).eq('id',id).select('*').single();if(r.error)throw r.error;await logActivity(client,actor.staffRow.id,actor.staffRow.full_name,'update_staff_account',id,updates);return r.data}if(action==='archive'||action==='delete'){if(!id||id===actor.staffRow.id)throw responseError('Invalid staff account',400);const r=await client.from('staff').update({is_active:false}).eq('id',id).select('*').single();if(r.error)throw r.error;await logActivity(client,actor.staffRow.id,actor.staffRow.full_name,'deactivate_staff_account',id);return r.data}if(action==='create'){const r=await client.from('staff').insert({id:txt(data.id),full_name:txt(data.full_name)||'Staff',role:txt(data.role)||'admin',branch:txt(data.branch)||'all',is_active:true}).select('*').single();if(r.error)throw r.error;await logActivity(client,actor.staffRow.id,actor.staffRow.full_name,'create_staff_account',String(r.data.id));return r.data}throw responseError('Unsupported staff action',400)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders(req)});try{const actor=await getActor(req);const c=actor.serviceClient;if(req.method==='GET'){if(!actor.canRead)return responseError('Forbidden',403,req);const kind=normalizeKind(new URL(req.url).searchParams.get('kind'));if(kind==='staff')return json(await listStaff(c),{},req);if(kind==='receipt')return json(await listReceipts(c),{},req);if(kind==='log')return json(await listLogs(c),{},req);if(kind==='shipment')return json(await listShipments(c),{},req);return json(await listCustomers(c),{},req)}if(req.method!=='POST')return responseError('Method not allowed',405,req);if(!actor.canWrite)return responseError('Forbidden',403,req);const body=(await req.json().catch(()=>({}))) as JsonRecord;const kind=normalizeKind(body.kind),action=normalizeAction(body.action),data=body.data&&typeof body.data==='object'?body.data as JsonRecord:body;if(kind==='customer')return json(await customerWrite(c,actor,action,data),{},req);if(kind==='staff')return json(await staffWrite(c,actor,action,data),{},req);return responseError('Unsupported action',400,req)}catch(error){if(error instanceof Response)return error;console.error('account-admin error',error);return json({error:error instanceof Error?error.message:String(error)},{status:500},req)}})
